name: Restore R16
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Note
        run: echo 'Use push_files instead'
